jobs:
  build:
    working_directory: ~/ex_wire
    docker:
      - image: elixir:latest
    steps:
      - run: apt-get update; apt-get -y install libgmp3-dev
      - checkout
      - restore_cache:
          key: _build
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      # TODO: The following step shouldn't be necessary.
      - run: cd deps/libsecp256k1 && rebar compile
      - run: mix test --exclude network
      - run: mix dialyzer
      - save_cache:
          key: _build
          paths:
            - _build
